    image: node:latest

    stages:
      - install
      - build
      - test

    cache:
      paths:
        - node_modules/
        - build/

    install_dependencies:
      stage: install
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    build:
      stage: build
      script: npm run build

    test:
      stage: test
      services:
        - postgres

      variables:
        POSTGRES_DB: vmtest
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "vennamesta"
      script:
        - docker-compose up -d 
        - npm test
      artifacts:
        paths:
          - node_modules/
