version: '3'
services:
  postgres:
    image: "postgres:10"
    container_name: "typeorm-postgres"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "vennamesta"
        POSTGRES_DB: vmtest
